description: fashion_mnist_tf_keras_const
hyperparameters:
  global_batch_size: 128
  lr: 0.004
  dense1: 128
records_per_epoch: 60000
resources:
  slots_per_trial: 2
searcher:
  name: single
  metric: val_accuracy
  smaller_is_better: false
  max_length:
    epochs: 5
entrypoint: model_def:FashionMNISTTrial
