# Validation Accuracy = 74%
description: cifar10_pytorch_fast
resources:
  slots_per_trial: 1
  resource_pool: k80-east-1a
hyperparameters:
  learning_rate: 0.0001
  global_batch_size: 32
  learning_rate_decay: 1e-6
  layer1_dropout: 0.25
  layer2_dropout: 0.25
  layer3_dropout: 0.5



records_per_epoch: 32
searcher:
  name: single
  metric: validation_accuracy
  smaller_is_better: false
  max_length:
    epochs: 2
max_restarts: 0
min_validation_period:
  epochs: 6
bind_mounts:
  - host_path: /tmp/
    container_path: /mnt/data
    read_only: false
entrypoint: model_def:CIFARTrial